import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Pizza Estaires",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body suppressHydrationWarning className="bg-[url(/assets/images/body-bg-img.webp)] bg-cover bg-no-repeat bg-top" >
        {children}
      </body>
    </html>
  );
}
